web:
  - changed-files: 
    - any-glob-to-any-file: 'apps/web/**/*'
mobile:
  - changed-files:
    - any-glob-to-any-file: 'apps/mobile/**/*'
pc:
  - changed-files:
    - any-glob-to-any-file: 'apps/pc/**/*'
docs:
  - changed-files:
    - any-glob-to-any-file: 'apps/docs/**/*'
packages:
  - any:
    - changed-files:
      - any-glob-to-any-file: 'packages/**/*'
common:
  - changed-files:
    - any-glob-to-any-file: '**/*'




